cadia-lvl/samromur

- src/components/contribute/carousel/wheel.tsx
- src/components/contribute/setup/contribute.tsx
- src/components/contribute/setup/demographic-form.tsx
- src/server/database/sentences.ts
- src/utilities/demographics-age-helper.ts
Also fixes a bug where the user got presented wrong sentence category when changing a previously set demographic.
> Random sentences improved

- src/components/competition/leaderboard.tsx
- src/components/contribute/setup/type-select.tsx
This allows us to be sure that the user only clicks once. And it gives feedback to the user that he/she has clicked the button.
> disable tala and hlusta on click

- src/components/competition/leaderboard.tsx
- src/components/contribute/setup/consent-form.tsx
- src/components/ui/animated/swipe.tsx
temp fix, the reusable component swipe has a bug that needs fixing
> format the consent for properly

- src/server/database/clips.ts
This adds speaker id generation to the db calls
> Speaker id db implementation

- .github/workflows/prettierformat.yaml
- package.json
Removing the auto re-format and commit when something is not complying with the prettier formatter.
> remove auto commit from format gh action

- src/components/contribute/setup/demographic-form.tsx
- src/constants/packages.ts
Some people in the Icelandic embassy in Paris want to show of Samrómur in a UNESCO event. Jóhanna asked for a small change to allow people to click on just two recs instead of 10. 
The event is happening sometime this week. We will change this back sometime next week.
> Small temp change

- src/components/contribute/carousel/controls/repeat-clip-play-button.tsx
Added an useEffect that triggers when the props.src has updated.
This updates the audio to play the correct source.
> Updade repeat clip audio

- src/components/contribute/carousel/wheel.tsx
- src/components/contribute/setup/contribute.tsx
- src/pages/api/contribute/verification-batches.ts
- src/server/database/clips.ts
- src/services/admin-api.ts
This pr does two things:
1. When running out of clips to verify, stop asking for new ones and update goal
2. In the list of verification batches, only display the ones that has clips that still needs verification.
> Batch verification upgrades

- src/components/contribute/carousel/controls/glow.ts
- src/components/contribute/carousel/controls/main-controls.tsx
- src/components/contribute/carousel/controls/repeat-clip-play-button.tsx
- src/components/contribute/carousel/wheel.tsx
- src/components/ui/input/text-input.tsx
- src/store/contribute/actions.ts
- src/store/contribute/reducer.ts
- src/store/contribute/state.ts
- src/store/ui/actions.ts
- src/utilities/id.ts
prevent from recording the repeated clips
> prevent recording of repeat clip

- src/components/contribute/setup/type-select.tsx
Enable herma now that we have sentences with clips in the db
> enable herma type select

- src/components/contribute/carousel/wheel.tsx
- src/components/layout/header/warning-modal.tsx
This fixes the issues david talked about.
Please review, and test that it works :)
> Herma modal delete fixes

- src/components/contribute/carousel/controls/main-controls.tsx
- src/components/contribute/carousel/controls/repeat-clip-play-button.tsx
- src/components/contribute/carousel/wheel.tsx
- src/constants/keyboardCommands.ts
This adds basic keyboardcommands to samromur
```
SpinForward = 'ArrowRight',
SpinBackward = 'ArrowLeft',
TogglePlayRecord = ' ', //space
VoteYes = 'q',
VoteNo = 'e',
VoteUnsure = 'r',
DeleteRecording = 'Delete',
Rerecord = 'x',
Skip = 's',
Submit = 'Enter',
PlayRepeatClip = 'a',
```
> Keyboard commands playground

- src/components/contribute/carousel/controls/main-controls.tsx
- src/constants/keyboardCommands.ts
This adds **w** as a keyboard shortcut to play/pause/record.
Also allows super users to execute early votes.
They can now vote up/down during clip play.
> Increase keyboard shortcuts functionality

- src/components/contribute/carousel/controls/main-controls.tsx
- src/components/contribute/carousel/wheel.tsx
disables keyboard commands during
> disable keyboard commands when expanded

- src/pages/_app.tsx
- src/pages/index.tsx
This should fix it so that users should never be "fake" logged in.
Should be able to test the difference in on samromur.is
* Log in, close page, then open homepage again -> not logged in properly (no hi message)
* Click mina sidur, automatically logged in -> see hi message instead of mina sidur
then while testing dev
* sign in, close page, open hompage again -> signed in, see hi message instead of mina sidur
> Bugfix client not logged in

- src/server/database/clips.ts
move it to the proper db call **fetchVerificationLabelsNeedingVotes**
> exclude lobe batch from batches

- src/components/dashboard/stats.tsx
Tiny fix to address this issue
> fix text going out of container

- src/server/database/stats.ts
Fixes a sql error that caused the server to crash while fetching weekly stats.
> return empty string when contribute type is hlusta

- next-env.d.ts
- next.config.js
- package-lock.json
- package.json
- public/static/locales/eng/cookies.md
- public/static/locales/eng/privacy-policy.md
- public/static/locales/eng/terms.md
- public/static/locales/isl/cookies.md
- public/static/locales/isl/privacy-policy.md
- public/static/locales/isl/terms.md
- src/components/charts/frontpage-stats.tsx
- src/components/dashboard/settings.tsx
- src/global.d.ts
- src/pages/personuverndaryfirlysing.tsx
- src/pages/skilmalar.tsx
- src/pages/vafrakokustefna.tsx
Main thing this is doing. Is allowing us to write a markdown article directly instead of writing these long text on a single line in a json file. The benefits speaks for themselves :smiley:
> Translations terms privacy policy

- src/components/contribute/carousel/instructions.tsx
- src/components/dataset/about.tsx
Switches the text for herma prompt to "endertaktu" instead of "lestu"
Add link to openSLR dataset
> Open slr link herma text

- public/static/locales/eng/demographics.json
- public/static/locales/isl/demographics.json
- src/components/contribute/setup/demographic-form.tsx
- src/constants/demographics.ts
- src/services/contribute-api.ts
- src/types/user.ts
@thdg 
Note, requires "icelandic_proficiency" column to be added to database clips table.
Note, please check my Icelandic in the localisation file (locales/isl/demographics.json)
- Asks user's Icelandic proficiency on demographic form.
- Automatically sets to "native" if mother tongue is Icelandic.
- uploadClip POST request now includes "icelandic_proficiency" in contribute-api.ts
> Added icelandic proficiency to frontend

- src/components/dashboard/stats.tsx
> make stats default to "-" instead of 0

- public/static/locales/eng/common.json
- public/static/locales/eng/l2.json
- public/static/locales/isl/common.json
- public/static/locales/isl/l2.json
- src/components/layout/header/navigation.tsx
- src/components/subpages/l2-sign-in-hello.tsx
- src/pages/l2.tsx
- src/pages/parallel.tsx
> English translations aug14

- src/pages/_app.tsx
> Add missing translations to initialProps for SSR

- public/static/locales/eng/l2.json
> fix typo in l2 prize text
